import {pgTable,serial,text,timestamp,integer,numeric,boolean,pgEnum,uniqueIndex,varchar,jsonb,index} from "drizzle-orm/pg-core";
export const role=pgEnum("role",["GESTOR","VENDEDOR"]); export const stage=pgEnum("stage",["PROSPECCAO","AGENDAMENTO","NEGOCIACAO","VENDA_GANHA","VENDA_PERDIDA"]); export const visitStatus=pgEnum("visit_status",["AGENDADA","REALIZADA","REMARCADA","NAO_RECEBEU","VENDA_GANHA","VENDA_PERDIDA","CANCELADA"]);
// Sessões persistentes geridas por server/session-store.ts. Deve constar no schema para que drizzle-kit push NUNCA tente apagar esta tabela.
export const userSessions=pgTable("user_sessions",{sid:varchar("sid").primaryKey(),sess:jsonb("sess").notNull(),expire:timestamp("expire",{withTimezone:true}).notNull()},t=>({expireIdx:index("user_sessions_expire_idx").on(t.expire)}));
export const users=pgTable("users",{id:serial("id").primaryKey(),name:text("name").notNull(),email:text("email").notNull().unique(),passwordHash:text("password_hash").notNull(),role:role("role").notNull().default("VENDEDOR"),active:boolean("active").notNull().default(true),googleRefreshToken:text("google_refresh_token"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const companies=pgTable("companies",{id:serial("id").primaryKey(),name:text("name").notNull(),cnpj:text("cnpj"),responsible:text("responsible"),phone:text("phone"),address:text("address"),employees:integer("employees"),email:text("email"),proposalValue:numeric("proposal_value",{precision:14,scale:2}),stage:stage("stage").notNull().default("PROSPECCAO"),inFunnel:boolean("in_funnel").notNull().default(true),ownerId:integer("owner_id").references(()=>users.id),proposalAt:timestamp("proposal_at",{withTimezone:true}),negotiationDeadline:timestamp("negotiation_deadline",{withTimezone:true}),wonAt:timestamp("won_at",{withTimezone:true}),lostAt:timestamp("lost_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>({cnpjIdx:uniqueIndex("companies_cnpj_unique").on(t.cnpj)}));
export const tags=pgTable("tags",{id:serial("id").primaryKey(),name:text("name").notNull().unique(),active:boolean("active").notNull().default(true),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const companyTags=pgTable("company_tags",{id:serial("id").primaryKey(),companyId:integer("company_id").notNull().references(()=>companies.id),tagId:integer("tag_id").notNull().references(()=>tags.id),addedBy:integer("added_by").notNull().references(()=>users.id),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const visits=pgTable("visits",{id:serial("id").primaryKey(),companyId:integer("company_id").notNull().references(()=>companies.id),sellerId:integer("seller_id").notNull().references(()=>users.id),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),status:visitStatus("status").notNull().default("AGENDADA"),reason:text("reason"),notes:text("notes"),googleEventId:text("google_event_id"),rescheduledToId:integer("rescheduled_to_id"),createdBy:integer("created_by").notNull().references(()=>users.id),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const routines=pgTable("routines",{id:serial("id").primaryKey(),sellerId:integer("seller_id").notNull().references(()=>users.id),title:text("title").notNull(),kind:text("kind").notNull().default("INTERNA"),notes:text("notes"),startsAt:timestamp("starts_at",{withTimezone:true}).notNull(),endsAt:timestamp("ends_at",{withTimezone:true}).notNull(),googleEventId:text("google_event_id"),cancelled:boolean("cancelled").notNull().default(false),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const followups=pgTable("followups",{id:serial("id").primaryKey(),companyId:integer("company_id").notNull().references(()=>companies.id),sellerId:integer("seller_id").notNull().references(()=>users.id),type:text("type").notNull(),notes:text("notes").notNull(),nextAt:timestamp("next_at",{withTimezone:true}),googleEventId:text("google_event_id"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const events=pgTable("audit_events",{id:serial("id").primaryKey(),companyId:integer("company_id").references(()=>companies.id),actorId:integer("actor_id").references(()=>users.id),type:text("type").notNull(),description:text("description").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()}); export const settings=pgTable("settings",{key:text("key").primaryKey(),value:text("value").notNull()});